"""Report model.

Maps to ``Report`` on the SDS class diagram. A report is generated from
audit log data, so it depends on ``AuditLogger`` only at call time, not at
import time, which keeps coupling low.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import List


@dataclass
class Report:
    report_id: int
    generated_by: int
    generated_date: datetime = field(default_factory=datetime.utcnow)
    body: str = ""

    def generate(self, entries: List[str]) -> str:
        """Render a plain-text report from a collection of audit entries."""
        header = (
            f"SDMS Audit Report #{self.report_id}\n"
            f"Generated by user {self.generated_by} "
            f"on {self.generated_date.isoformat(timespec='seconds')}\n"
            f"{'-' * 60}\n"
        )
        self.body = header + "\n".join(entries)
        return self.body

    def download(self) -> bytes:
        return self.body.encode("utf-8")
